workspace:
  base: /var/www/owncloud
  path: apps/testing

branches:
  - master

pipeline:
  install-core:
    image: owncloudci/core
    pull: true
    exclude:
      - apps/testing
    version: ${OC_VERSION}
    db_type: ${DB_TYPE}
    db_name: ${DB_NAME=owncloud}
    db_host: ${DB_TYPE}
    db_username: autotest
    db_password: owncloud
    when:
      matrix:
        NEED_CORE: true

  install-testrunner:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - git clone -b stable10 --depth=1 https://github.com/owncloud/core.git /var/www/owncloud/testrunner
      - cp -r /var/www/owncloud/apps/testing /var/www/owncloud/testrunner/apps/
      - cd /var/www/owncloud/testrunner
      - make install-composer-deps
      - make vendor-bin-deps
    when:
      matrix:
        USE_RELEASE_TARBALL: true

  install-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/testing/.cache/composer
    commands:
      - make vendor
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=owncloud
      - php occ a:e testing
      - php occ a:l
    when:
      matrix:
        NEED_INSTALL_APP: true

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /var/www/owncloud/data/owncloud.log

  fix-permissions:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - chown www-data /var/www/owncloud -R
      - if [ "${USE_RELEASE_TARBALL}" = "true" ];
        then
        chmod 777 /var/www/owncloud/testrunner/tests/acceptance/filesForUpload -R;
        chmod +x /var/www/owncloud/testrunner/tests/acceptance/run.sh;
        else
        chmod 777 /var/www/owncloud/tests/acceptance/filesForUpload -R;
        chmod +x /var/www/owncloud/tests/acceptance/run.sh;
        fi
    when:
      matrix:
        NEED_SERVER: true

  owncloud-coding-standard:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-style
    when:
      matrix:
        TEST_SUITE: owncloud-coding-standard

  phpstan:
    # phpstan requires php7.1
    image: owncloudci/php:7.1
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/testing/.cache/composer
    commands:
      - make test-php-phpstan
    when:
      matrix:
        TEST_SUITE: phpstan

  phan:
    # phan requires a recent php-ast extension
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/testing/.cache/composer
    commands:
      - make test-php-phan
    when:
      matrix:
        TEST_SUITE: phpunit
        PHAN: true

  phpunit-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - COVERAGE=${COVERAGE}
    commands:
      - if [ -z "${COVERAGE}" ]; then make test-php-unit; fi
      - if [ "${COVERAGE}" = "true" ]; then make test-php-unit-dbg; fi
    when:
      matrix:
        TEST_SUITE: phpunit

  api-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - TEST_SERVER_URL=http://owncloud
      - PLATFORM=Linux
      - BEHAT_SUITE=${BEHAT_SUITE}
    commands:
      - if [ "${USE_RELEASE_TARBALL}" = "true" ]; then cd /var/www/owncloud/testrunner/apps/testing; fi
      - make test-acceptance-api
    when:
      matrix:
        TEST_SUITE: api-acceptance

  build:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make dist
    when:
      matrix:
        TEST_SUITE: build

  github_release:
    image: plugins/github-release
    pull: true
    secrets: [ github_token ]
    files: build/dist/testing.tar.gz
    prerelease: true
    file_exists: overwrite
    checksum: sha256
    when:
      event: tag
      matrix:
        TEST_SUITE: build

  notify:
    image: plugins/slack:1
    pull: true
    secrets: [slack_webhook]
    channel: builds
    when:
      status: [failure, changed]
      event: [push, tag]

services:
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_USER=autotest
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=${DB_NAME=owncloud}
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql

  pgsql:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=autotest
      - POSTGRES_PASSWORD=owncloud
      - POSTGRES_DB=${DB_NAME=owncloud}
    when:
      matrix:
        DB_TYPE: pgsql

  oci:
    image: deepdiver/docker-oracle-xe-11g
    environment:
      - ORACLE_USER=system
      - ORACLE_PASSWORD=oracle
      - ORACLE_DB=${DB_NAME=owncloud}
    when:
      matrix:
        DB_TYPE: oci

  owncloud:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: ["/usr/local/bin/apachectl", "-e", "debug", "-D", "FOREGROUND"]
    when:
      matrix:
        NEED_SERVER: true

matrix:
  include:
    # owncloud-coding-standard
    - PHP_VERSION: 7.0
      TEST_SUITE: owncloud-coding-standard

    # phpstan
    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpstan
      NEED_CORE: true
      NEED_INSTALL_APP: true

    # build
    - PHP_VERSION: 7.2
      TEST_SUITE: build

    # Unit Tests
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite
      NEED_CORE: true
      PHAN: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      NEED_CORE: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: pgsql
      NEED_CORE: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: oci
      DB_NAME: XE
      NEED_CORE: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      NEED_CORE: true
      PHAN: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite
      NEED_CORE: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      NEED_CORE: true
      PHAN: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: pgsql
      NEED_CORE: true
      COVERAGE: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: oci
      DB_NAME: XE
      NEED_CORE: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      NEED_CORE: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      NEED_CORE: true

    # Acceptance Tests
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiTestingApp
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiTestingApp
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiTestingApp
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiTestingApp
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiTestingApp
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true

  # Acceptance tests against latest stable release of core
    - PHP_VERSION: 7.1
      OC_VERSION: 10.2.1
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiTestingApp
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      USE_RELEASE_TARBALL: true
